#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# nitrogen --set-scaled Pictures/Wallpapers/human.jpg
feh --bg-fill ~/Pictures/Wallpapers/arch_gruvboxdark.png &

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

killall picom; picom -b --experimental-backends &

# ~/.config/polybar/launch.sh &
$HOME/.config/polybar/launch.sh --blocks &

dunst &
pamac-tray &
flameshot &
killall volumeicon; volumeicon &
# xfce4-power-manager &
nm-applet &
blueman-applet &

xsetroot -cursor_name left_ptr &


xss-lock -- i3lock -e -t -i ~/Pictures/Wallpapers/moon.png &
xset dpms 180 300 &

bspc config remove_disabled_monitors true
bspc config focus_follows_pointer true
bspc config merge_overlapping_monitors true

#Single monitor
bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9

#Dual monitor
#find out names with arandr or xrandr
# xrandr --output HDMI-1 1366x768 --right-of eDP-1
#bspc monitor DP-2 -d 1 2 3 4 5 6 7 8 9
#bspc monitor LVDS1 -d 1 2 3 4
#bspc monitor DP3 -d  5 6 7 8 9
#bspc monitor HDMI-0 -d 1 2 3 4 5 6 7 8 9 10
# bspc monitor HDMI-1 -d 6 7 8 9 10
#bspc monitor HDMI1 -d 1 2 3 4 5
#bspc monitor HDMI2 -d 6 7 8 9 10

bspc config border_width    2
bspc config window_gap      2
bspc config top_padding     30
bspc config right_padding   0
bspc config left_padding    0
bspc config bottom_padding  0

bspc config split_ratio     0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config single_monocle                false
bspc config auto_alternate true
bspc config auto_cancel true
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.0

bspc config pointer_follows_focus true
#bspc config focus_by_distance    true
bspc config focus_follows_pointer false
#bspc config history_aware_focus  true
bspc config history_aware_focus           true

bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true

bspc config normal_border_color "#AC8476" #gray
bspc config active_border_color "#FFFFFF" #white
bspc config focused_border_color "#75A4CD" #blue
bspc config presel_border_color "75A4CD" #blue
bspc config urgent_border_color "#EC7875" #red
bspc config focused_locked_border_color "EBD369" #yellow

bspc rule -a Zathura state=tiled

#open applications on specific workspaces
bspc rule -a Firefox desktop='^2' follow=on
bspc rule -a google-chrome-stable desktop='^2' follow=on
bspc rule -a Chromium desktop='^2' follow=on
bspc rule -a discord desktop='^4' follow=on
bspc rule -a nautilus desktop='^3' follow=on
bspc rule -a telegram-desktop desktop='^4' follow=on
bspc rule -a Skype pseudo_tiled=on
bspc rule -a Spotify pseudo_tiled=on
bspc rule -a Thunar pseudo_tiled=on
bspc rule -a Nautilus pseudo_tiled=on
bspc rule -a Skype pseudo_tiled=on
bspc rule -a File-roller pseudo_tiled=on
bspc rule -a Transmission-gtk pseudo_tiled=on
# bspc rule -a Conky sticky=on manage=off lower=on
bspc rule -a feh floating=on manage=off

#Spotify fix  --move desktop 10
#sleep 1
#wmctrl -r Spotify -t 10
#exit
